import PDFDocument from 'pdfkit';
import { Invoice } from '../types/invoice.js';

interface ContractorInfo {
  first_name: string;
  last_name: string;
  email: string;
  wallet_address?: string;
}

export class InvoicePDFService {
  generateInvoicePDF(invoice: Invoice, contractorInfo: ContractorInfo): PDFKit.PDFDocument {
    const doc = new PDFDocument({ margin: 50 });

    // Header
    doc.fontSize(20).text('INVOICE', { align: 'center' });
    doc.moveDown();

    // Invoice details
    doc.fontSize(10);
    doc.text(`Invoice Number: ${invoice.invoice_number}`, { align: 'right' });
    doc.text(`Date: ${new Date(invoice.submitted_at).toLocaleDateString()}`, { align: 'right' });
    doc.text(`Status: ${invoice.status.toUpperCase()}`, { align: 'right' });
    doc.moveDown();

    // Contractor info
    doc.fontSize(12).text('From:', { underline: true });
    doc.fontSize(10);
    doc.text(`${contractorInfo.first_name} ${contractorInfo.last_name}`);
    doc.text(contractorInfo.email);
    if (contractorInfo.wallet_address) {
      doc.text(`Wallet: ${contractorInfo.wallet_address}`);
    }
    doc.moveDown();

    // Line items
    doc.fontSize(12).text('Invoice Details:', { underline: true });
    doc.moveDown(0.5);

    const tableTop = doc.y;
    doc.fontSize(10);
    
    // Table headers
    doc.text('Description', 50, tableTop, { width: 200 });
    doc.text('Hours', 270, tableTop, { width: 80 });
    doc.text('Rate', 360, tableTop, { width: 80 });
    doc.text('Amount', 450, tableTop, { width: 100, align: 'right' });
    
    doc.moveTo(50, tableTop + 15).lineTo(550, tableTop + 15).stroke();
    
    // Table content
    const itemY = tableTop + 25;
    doc.text(invoice.description || 'Contractor Services', 50, itemY, { width: 200 });
    doc.text(invoice.hours.toFixed(2), 270, itemY, { width: 80 });
    doc.text(`${invoice.rate.toFixed(2)} ${invoice.currency}`, 360, itemY, { width: 80 });
    doc.text(`${invoice.total_amount.toFixed(2)} ${invoice.currency}`, 450, itemY, { width: 100, align: 'right' });
    
    doc.moveDown(3);
    doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
    doc.moveDown(0.5);

    // Total
    doc.fontSize(12);
    doc.text(`Total: ${invoice.total_amount.toFixed(2)} ${invoice.currency}`, { align: 'right' });
    doc.moveDown();

    // Payment status
    if (invoice.status === 'paid' && invoice.payment_tx_hash) {
      doc.fontSize(10);
      doc.text('Payment Details:', { underline: true });
      doc.text(`Transaction Hash: ${invoice.payment_tx_hash}`);
      doc.text(`Paid on: ${invoice.reviewed_at ? new Date(invoice.reviewed_at).toLocaleDateString() : 'N/A'}`);
    }

    // Footer
    doc.fontSize(8).text(
      'This invoice was generated by PayD - Stellar-Based Cross-Border Payroll Platform',
      50,
      doc.page.height - 50,
      { align: 'center' }
    );

    return doc;
  }
}

export const invoicePDFService = new InvoicePDFService();
